### ISSUE TITLE
Design review for v15

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/Arduino_Pro_Mini_328#1]
1) Is there a SparkFun Logo? [NO]
comment: Missing logo in sch

2) Is there an OSHW logo? [NO]
comment: missing oshw logo in sch

3) If net labels are used, are they the correct 'FLAG' type? [NO]
comment: A4 and A5 nets off the micro pins could use some flag labels

4) Are dashed grey lines ('info' eagle layer 97) used to clearly separate different areas? [NO]
comment: could be better

5) Do all GND connections use the GND symbol (oriented downward)? [NO]
comment: nets off of JP1, JP7 and JP6

6) Do all VCC connections use the VCC symbol (oriented upward)? [NO]
comment: nets off of JP1 and JP6

7) Is the VCC range clearly labeled? [NO]
comment: Yes, but RAW input range would be useful too

8) Have you verified that the BOM in Sparkle is accurate (also checking for PROD_ID, NAME, VALUE, PREFIX)? [NO]
comment: no PROD_IDs on anything.  value on Q1 should loose the "20MHz", and U1 could use a "ATMEGA328P" (note the "P"), LED1 should be a "D"

9) Do any parts have unnecessary values (Eagle has autoset the package as the value)? [YES]
comment: JP6, JP7

10) Is there a note for a board thickness other than 0.63 inch?  [YES]
comment: I like the large text, but putting in "0.8mm thickness" is what most people are used to, I think both the large text and the number would be great.

11) Is there a URL for any kits or unique boards? [YES]
comment: asked at bug, but it might be a good idea to put the landing page for this product on the bottom silk...

**Comment by marshalltaylorSFE** [comment]
These changes were not requested, trying again
